
-- 1/27 ----------------------------------------------

GRANT CREATE USER TO kim;

SELECT * FROM DBA_USERS; -- DBA는 관리자만 쓸수있음

GRANT CONNECT, RESOURCE,UNLIMITED TABLESPACE TO TEST;

ALTER USER TEST ACCOUNT LOCK; --계정 잠금

ALTER USER TEST IDENTIFIED BY ABC ACCOUNT UNLOCK; --계정 풀고 비밀번호 변경

REVOKE CREATE USER FROM kim; -- 권한뺏기


/*
권한의 종류

SYSTEM 권한 : DATABASE의 OBJECT들을 생성(CREATE), 수정(ALTER), 삭제(DROP) 할수 있는 권한.
				DBA -> USER

OBJECT 권한 : OBJECT 내용을 추가(INSERT),변경(UPDATE), 삭제(DELETE), 검색(SELECT)할수 있는 권한
				USER -> USERS

OBJECT : TABLE, SEQUENCE, VIEW
*/

--시스템 권한은 어떤것들이 있습니까?
SELECT * FROM SYSTEM_PRIVILEGE_MAP;

GRANT CREATE SESSION,RESOURCE,UNLIMITED TABLESPACE TO SUZI; --수지에게 권한 부여

REVOKE CREAT RESOURCE,UNLIMITED TABLESPACE FROM SUZI; --수지에게서 권한 회수

GRANT CREATE SESSION,RESOURCE,UNLIMITED TABLESPACE TO KIM;

GRANT CREATE ROLE TO KIM;

CREATE ROLE MANAGER;

GRANT CREATE USER, CREATE VIEW TO MANAGER;

SELECT * FROM DBA_ROLES;

SELECT * FROM ROLE_SYS_PRIVS
WHERE ROLE='MANAGER';

GRANT MANAGER TO SUZI;

REVOKE MANAGER FROM SUZI;

GRANT CREATE VIEW TO KIM; 



